import { Shield, AlertCircle } from 'lucide-react';

export default function TermsOfService() {
  return (
    <main className="max-w-3xl mx-auto px-6 py-16 sm:py-24">
      <article className="prose prose-invert max-w-none">
        <header className="mb-8">
          <h1 className="font-display text-4xl sm:text-5xl mb-4">Terms of Service</h1>
          <p className="text-bone/60">
            Last updated: {new Date().toLocaleDateString()}
          </p>
        </header>

        <AlertCircle className="w-8 h-8 text-mist mb-6" />
        
        <section className="mb-8">
          <h2 className="font-display text-xl mb-4 flex items-center gap-2">
            <Shield className="w-5 h-5 text-brass" />
            1. Service Description
          </h2>
          <p className="text-sm text-bone/70 leading-relaxed">
            Caliber provides an Instagram profile audit service for dating purposes. We analyze your existing Instagram profile to provide feedback on photos, bio content, and overall presentation that may help attract better matches. The audit is generated by AI analysis of screenshots you provide — we do not access your account directly.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="font-display text-xl mb-4 flex items-center gap-2">
            <Shield className="w-5 h-5 text-brass" />
            2. User Accounts
          </h2>
          <p className="text-sm text-bone/70 leading-relaxed mb-3">
            To use Caliber, you must create an account by providing a valid email address and password. You are responsible for maintaining the security of your account credentials.
          </p>
          <ul className="list-disc pl-5 space-y-1 text-sm text-bone/70">
            <li>You must be at least 18 years old to use our services.</li>
            <li>We may suspend or terminate accounts that violate these terms.</li>
            <li>You may request account deletion via email to support@caliger.com.</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="font-display text-xl mb-4 flex items-center gap-2">
            <Shield className="w-5 h-5 text-brass" />
            3. Data Processing
          </h2>
          <p className="text-sm text-bone/70 leading-relaxed mb-3">
            When you use Caliber:
          </p>
          <ul className="list-disc pl-5 space-y-1 text-sm text-bone/70">
            <li>Your Instagram screenshots are processed by our AI system to generate audit results.</li>
            <li>Processed data is automatically deleted within 24 hours — we never store your photos.</li>
            <li>Your email and account metadata may be retained as required for service delivery and legal compliance.</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="font-display text-xl mb-4 flex items-center gap-2">
            <Shield className="w-5 h-5 text-brass" />
            4. Service Limitations & Disclaimers
          </h2>
          <p className="text-sm text-bone/70 leading-relaxed mb-3">
            CALIBER IS AN INFORMATIONAL TOOL ONLY:
          </p>
          <ul className="list-disc pl-5 space-y-1 text-sm text-bone/70">
            <li>We do not guarantee any specific outcomes from using our service.</li>
            <li>Your dating success depends on many factors beyond your profile presentation.</li>
            <li>We make no warranties about the accuracy of audit results — they are based on AI analysis patterns.</li>
            <li>We are not responsible for any third-party claims regarding content we display from public Instagram profiles.</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="font-display text-xl mb-4 flex items-center gap-2">
            <Shield className="w-5 h-5 text-brass" />
            5. Payment Terms
          </h2>
          <p className="text-sm text-bone/70 leading-relaxed mb-3">
            Caliber is processed by Stripe. All payments are subject to Stripe's terms and your acceptance of billing fees. Free tier users receive one audit per day; paid tier users receive up to five audits per day with additional features.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="font-display text-xl mb-4 flex items-center gap-2">
            <Shield className="w-5 h-5 text-brass" />
            6. Refund Policy (Pending Stripe Integration)
          </h2>
          <p className="text-sm text-bone/70 leading-relaxed">
            We are currently in a limited beta period. Once our payment system launches, we may offer refunds within 30 days of purchase for technical issues or unmet service expectations. Refund requests should be emailed to support@caliger.com with your order number.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="font-display text-xl mb-4 flex items-center gap-2">
            <Shield className="w-5 h-5 text-brass" />
            7. Intellectual Property
          </h2>
          <p className="text-sm text-bone/70 leading-relaxed">
            All content on Caliger (including code, design, and documentation) is owned by or licensed to us. Your audit results are yours to keep — feel free to share them with potential dates as you choose.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="font-display text-xl mb-4 flex items-center gap-2">
            <Shield className="w-5 h-5 text-brass" />
            8. Third-Party Links
          </h2>
          <p className="text-sm text-bone/70 leading-relaxed">
            We may display links to third-party resources (e.g., dating advice content). We are not responsible for the practices of such sites. Clicking third-party links is subject to their own terms and privacy policies.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="font-display text-xl mb-4 flex items-center gap-2">
            <Shield className="w-5 h-5 text-brass" />
            9. Acceptable Use
          </h2>
          <p className="text-sm text-bone/70 leading-relaxed">
            You agree not to use Caliber for:
          </p>
          <ul className="list-disc pl-5 space-y-1 text-sm text-bone/70">
            <li>Harassment, threats, or harmful behavior toward others</li>
            <li>Spreading malware or attempting unauthorized system access</li>
            <li>Automated scraping or bypassing our rate limits</li>
            <li>Violating Instagram's Terms of Service in any way</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="font-display text-xl mb-4 flex items-center gap-2">
            <Shield className="w-5 h-5 text-brass" />
            10. Limitation of Liability
          </h2>
          <p className="text-sm text-bone/70 leading-relaxed">
            Caliger operates as-is without warranty. We are not liable for any indirect, incidental, or consequential damages arising from your use of our services, including lost time, data, or opportunities. Our total liability is limited to the amount you paid for affected subscriptions.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="font-display text-xl mb-4 flex items-center gap-2">
            <Shield className="w-5 h-5 text-brass" />
            11. Governing Law
          </h2>
          <p className="text-sm text-bone/70 leading-relaxed">
            These terms are governed by California law. Any disputes will be resolved in California state courts unless you agree otherwise.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="font-display text-xl mb-4 flex items-center gap-2">
            <Shield className="w-5 h-5 text-brass" />
            12. Changes to These Terms
          </h2>
          <p className="text-sm text-bone/70 leading-relaxed">
            We may update these terms occasionally. Material changes will be posted with a notice date on our website. Continued use after changes constitutes acceptance of updated terms.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="font-display text-xl mb-4 flex items-center gap-2">
            <Shield className="w-5 h-5 text-brass" />
            13. Contact
          </h2>
          <p className="text-sm text-bone/70 leading-relaxed">
            Questions about these terms? Email us at{' '}
            <a href="mailto:support@caliger.com" className="text-brass underline decoration-dotted">
              support@caliger.com
            </a>
          </p>
        </section>

        <footer className="pt-8 border-t border-hair mt-12">
          <Link href="/signup" className="inline-block px-6 py-3 bg-brass text-ink font-medium rounded-lg hover:bg-brass/90 transition-colors mb-4">
            Create Account
          </Link>
          <p className="text-xs text-mist">
            By using our services, you agree to these Terms of Service and our Privacy Policy.
          </p>
        </footer>
      </article>
    </main>
  );
}
